name: Kics Infrastructure as Code Security Scan

on:
  push:
  workflow_dispatch:
  
jobs:
  Kicks-iac-security:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job...
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: mkdir -p myResults
      # Scan Iac with kics
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.4
      with:
        # scanning two directories: ./terraform/ ./cfn-templates/ plus a single file
        path: 'terraform/aws/db.tf'
        output_path: myResults/
        output_formats: sarif
        ignore_on_exit: results
        
        #Uploading the artifacts in Github actions
    -  name: Use the Upload Artifact GitHub Action
       uses: actions/upload-artifact@v2
       with:
           name: results.sarif
           path: myResults/results.sarif
